# Generated by Django 4.1 on 2022-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_alter_post_content_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='post_images', verbose_name='Image'),
        ),
    ]
